/*****Create a TABLE MOVIE *****/

CREATE TABLE MOVIE(MOVIEID INT PRIMARY KEY, TITLE VARCHAR(255), RELEASE_YEAR INT, GENRES VARCHAR(500));

/*****Create a TABLE MOVIE *****/

CREATE TABLE RATING(USERID INT, MOVIEID INT, RATING DOUBLE, UPDATED_ON BIGINT);

/*****Add FOREIGN KEY to TABLE MOVIE *****/

ALTER TABLE RATING ADD FOREIGN KEY (MOVIEID) REFERENCES MOVIE(MOVIEID);

/*****Create a TABLE MOVIE *****/

CREATE TABLE TAG(USERID INT, MOVIEID INT, TAG VARCHAR(400), UPDATED_ON BIGINT);

/*****Add FOREIGN KEY to TABLE TAG *****/

ALTER TABLE TAG ADD FOREIGN KEY (MOVIEID) REFERENCES MOVIE(MOVIEID);

/*****Create a TABLE LINK *****/

CREATE TABLE LINK(MOVIEID INT, IMDB_ID VARCHAR(100), TMDB_ID VARCHAR(100));

/*****Add FOREIGN KEY to TABLE MOVIE *****/

ALTER TABLE LINK ADD FOREIGN KEY (MOVIEID) REFERENCES MOVIE(MOVIEID);

/*****Create a TABLE GENOME_TAGS *****/

CREATE TABLE GENOME_TAGS(TAG_ID INT PRIMARY KEY, TAG_NAME VARCHAR(255));

/*****Create a TABLE GENOME_SCORES *****/

CREATE TABLE GENOME_SCORES(MOVIEID INT, TAG_ID INT, RELEVANCE DOUBLE);

/*****Add FOREIGN KEY to TABLE GENOME_SCORES *****/

ALTER TABLE GENOME_SCORES ADD FOREIGN KEY (MOVIEID) REFERENCES MOVIE(MOVIEID);

/*****Add FOREIGN KEY to TABLE GENOME_SCORES *****/

ALTER TABLE GENOME_SCORES ADD FOREIGN KEY (TAG_ID) REFERENCES GENOME_TAGS(TAG_ID);


